Added double timer with adaptive design. Placed at <Layout/> just to …
okolobaha-me/goit-team-project-frontend pull request #11
Opened 2022-10-02 08:22 UTC by SergiyRybin

Added double timer with adaptive design. Placed at <Layout/> just to visualization. Before merge with main will need to move in right place.

2022-10-02 08:51 UTC, okolobaha-me requested changes
оставил ревью

2022-10-02 08:51 UTC, okolobaha-me commented on src/components/Timer/Timer.jsx
> +    const defaultValueOnTimer = {
сомневаюсь что с бэка тебе будет приходить такого вида объект
твой компонент должен принимать дату которая будет приходить с бека
и тут должен быть код который будет считать время оставшееся до этой даты
я уже установил либо date fns используй ее для логики

2022-10-02 08:51 UTC, okolobaha-me commented on src/components/Timer/Timer.jsx
> +    return (
и что это за хардкокд 
таймер это должен быть компонент  с ОДНИМ отстетом  
в этот компонент просто пробрасывается дата и он считает .... как выше писал вобщем
а на странице уже там где надо будут вставлять этот компонент 
и если  надо вставят 2 раза с разными значениям 
в иделе кстати сделать что бы можно было передавать дату или нет
и если ее не передавать выполняется скрипт считающий время до ближайшего нг

2022-10-02 08:53 UTC, SergiyRybin commented on src/components/Timer/Timer.jsx
> +    const defaultValueOnTimer = {
Задача була створити розмітку. Я перепитував.

2022-10-02 16:57 UTC, SergiyRybin commented on src/components/Timer/Timer.jsx
> +    return (
Додав логіку таймера. Виніс в окремий компонент. Питання по формату який буде приходити із бека.

2022-10-02 18:45 UTC, okolobaha-me requested changes
нудны правки

2022-10-02 18:45 UTC, okolobaha-me commented on src/components/Timer/Timer.jsx
> +                <TimerLogic />
поменять пестами
плюс доработатьстили 
на таблетке не совпадает маржин между таймерами
он должен быть меньше чем на десктопе

2022-10-02 18:45 UTC, okolobaha-me commented on src/components/Timer/Timer.styled.jsx
> +export const TimerTitle = styled.div`
какой же это дав если это должен быть какой нить h3 ну или p хотя бы

2022-10-02 18:45 UTC, okolobaha-me commented on src/components/Timer/Timer.styled.jsx
> +    flex-direction: column;
зачем делать TimerNumber и TimerDays спанами а потом писать эти flex column
можно убрать флексы заменить спан на п и все будет работать без лишних стилей

2022-10-02 18:45 UTC, okolobaha-me commented on src/components/Timer/Timer.styled.jsx
> +    margin: 0 10px;
не замечание а совет: 
почитай про свойство "gap"
это поможет избавится от этих маржинов и всяких нот ласт чаилд итд 

а вот зачмечание: 
зачем вешать маржины с обеих сторон. лишний раз считать по сколоко их надо сделать (потому что тебе приходится делать их вдвое меньше чем на макете что бы получить желаемое ) итд 
если ты можешь столать просто - нот ласт чаилд маржин райт....

2022-10-02 18:45 UTC, okolobaha-me commented on src/components/Timer/Timer.styled.jsx
> +        margin-right: 74px;
тоже вместо перебивания правил у последнего ребенка сделай через нот ласт чаилд

2022-10-02 18:45 UTC, okolobaha-me commented on src/components/Timer/Timer.styled.jsx
> +        &:first-of-type {
не понял в чем вообще смысл этого перебивания

2022-10-02 18:45 UTC, okolobaha-me commented on src/components/Timer/TimerLogic.jsx
> +        updateTimer();
таймер надо почистить при анмаунте

2022-10-02 18:45 UTC, okolobaha-me commented on src/components/Timer/TimerLogic.jsx
> +
логика вродь конечно работает нормально НО 
у нас есть date-fns библиотека которая оч хорошо оптимизирована и оч много удобных инструментов готовых 
лучше использовать ее все таки

2022-10-03 18:25 UTC, SergiyRybin commented on src/components/Timer/TimerLogic.jsx
> +
привет. Немає часу розбиратись із бібліотекою на роботі завал. Можливо краще було б краще її використовувати, вона переваре більше форматів. Якщо не горить в на протязі пару днів перепишу. Якщо ні, то ні. Розмітку підправив, не все там ідеально. Подивись, будь ласка але часу не вистачає нажаль.

2022-10-03 18:29 UTC, merged