add library form
okolobaha-me/goit-team-project-frontend pull request #3
Opened 2022-09-26 18:10 UTC by ElenaLukashevych

2022-09-26 18:22 UTC, okolobaha-me requested changes
замени width в кнопке на min-width

2022-09-26 18:22 UTC, okolobaha-me commented on src/components/FormLibrary/FormLibrary.styled.jsx
> +    width: 171px;
жостко задавать  ширину кнопке плохая мода. если вдруг измениться контент сломается и верстка. желательно падингами и контентом регулировать шириту. в худшем случае Min-width

2022-09-26 18:22 UTC, okolobaha-me commented on src/components/FormLibrary/FormLibrary.styled.jsx
> +        width: 181px;
туда же

2022-09-26 18:48 UTC, iPanamas reviewed
good s tebya shaurma

2022-09-27 06:00 UTC, okolobaha-me approved these changes

2022-09-27 06:00 UTC, merged